// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxQBewvSw2JIaJ4GvyNIlWqSLR9yyVr8',
    appId: '1:137823149236:web:e037fcc2ec8fdee5988be1',
    messagingSenderId: '137823149236',
    projectId: 'sumit-firebase-d11f2',
    authDomain: 'sumit-firebase-d11f2.firebaseapp.com',
    storageBucket: 'sumit-firebase-d11f2.firebasestorage.app',
    measurementId: 'G-LVZB1CGS2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzF9xDvhQhAGZJk0RVplRWFn6vkPJxE2U',
    appId: '1:137823149236:android:390bb4635496c220988be1',
    messagingSenderId: '137823149236',
    projectId: 'sumit-firebase-d11f2',
    storageBucket: 'sumit-firebase-d11f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3_2OktUcp64tAxe7zE5AECP3nxfAoe2g',
    appId: '1:137823149236:ios:7552ecd363cdf11a988be1',
    messagingSenderId: '137823149236',
    projectId: 'sumit-firebase-d11f2',
    storageBucket: 'sumit-firebase-d11f2.firebasestorage.app',
    iosClientId: '137823149236-e8dvolr6ne800qcicusrs58m6pnsl360.apps.googleusercontent.com',
    iosBundleId: 'sumitsaw.tech.sumitOcs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3_2OktUcp64tAxe7zE5AECP3nxfAoe2g',
    appId: '1:137823149236:ios:7552ecd363cdf11a988be1',
    messagingSenderId: '137823149236',
    projectId: 'sumit-firebase-d11f2',
    storageBucket: 'sumit-firebase-d11f2.firebasestorage.app',
    iosClientId: '137823149236-e8dvolr6ne800qcicusrs58m6pnsl360.apps.googleusercontent.com',
    iosBundleId: 'sumitsaw.tech.sumitOcs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvxQBewvSw2JIaJ4GvyNIlWqSLR9yyVr8',
    appId: '1:137823149236:web:7d9ac7f325ff125d988be1',
    messagingSenderId: '137823149236',
    projectId: 'sumit-firebase-d11f2',
    authDomain: 'sumit-firebase-d11f2.firebaseapp.com',
    storageBucket: 'sumit-firebase-d11f2.firebasestorage.app',
    measurementId: 'G-885WY6NETW',
  );
}
